# Pre-commit configuration file for Git hooks
# This file defines automated checks that run before each commit

repos:
  # Standard pre-commit hooks for basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: trailing-whitespace  # Trims trailing whitespace from all lines

  # Markdown linting to ensure consistent style
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint  # Checks Markdown files for style issues
        files: \.(md|md\.jinja)$  # Apply to both .md and .md.jinja files

  # Spell checking for code and documentation
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos  # Checks for spelling mistakes
        exclude: '\.gitignore$'  # Skip checking .gitignore files
