# Workflow to create a new tag and release based on user input
# This workflow is manually triggered via the GitHub UI

name: Create Tag and Release
on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)


jobs:
  # Job to create and push a tag based on user input
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.set_tag.outputs.tag }}  # Output the tag to be used by other jobs

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

      # Create a GitHub release for the tag
      # This creates a release on GitHub with automatically generated release notes
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.3.2  # Third-party release action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
          tag_name: ${{ github.event.inputs.tag }}  # Use the provided tag
          generate_release_notes: true  # Automatically generate notes from commits

  marimo:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    permissions:
      contents: read
    steps:
      - uses: jebel-quant/marimushka/@v0.1.4
        with:
          notebooks_wasm: ''
          notebooks: 'marimo'
          apps: ''

  book:
    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin
    runs-on: ubuntu-latest
    needs: [ marimo ]           # This job depends on both jupyter and marimo jobs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish book    # specify the path to avoid direct exposure of marimushka
        id: deployment
        uses: tschm/cradle/actions/book@v0.3.06
        with:
          title: "My project"
          links: |
            {
              "Notebooks": "./marimushka/index.html"
            }
