# Workflow to automatically bump the version and create a new tag
# This workflow is manually triggered via the GitHub UI

name: Bump version and publish

on:
  workflow_dispatch:  # Manual trigger

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)

jobs:
  # Job to generate a new version tag
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}  # Output the new tag to be used by other jobs

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.71  # Custom action to generate a new tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication

  html:
    runs-on: ubuntu-latest
    needs: tagging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r "requirements.txt"

      - name: Export notebook to static HTML presentation
        run: |
          mkdir -p dist
          marimo export html marimo/notebook.py --no-include-code -o dist/notebook.html

      - name: Export notebook via wasm
        run: |
          mkdir -p dist/wasm
          # export as readonly, with code locked
          marimo export html-wasm marimo/notebook.py -o dist/wasm --mode run

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tagging.outputs.new_tag }}
          generate_release_notes: true
          files: dist/notebook.html

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages                # The branch the action should deploy to.
          folder: dist/wasm               # The folder the action should deploy
